config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
 

  get 'login' => 'recursers#start_auth'

  post 'auth/start' => 'recursers#start_auth'
  get 'auth/callback' => 'recursers#auth_callback'

  patch 'recursers/:id/leave_group' => "recursers#leave_group"

  
  

  resources :groups
  resources :recursers, :only => [:new, :create]

  get 'profile' => "recursers#edit"
  patch 'profile' => "recursers#update"
  
  

  

end

app/models/available_time.rb
class AvailableTime < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :recursers, inverse_of: :group
  has_one :available_time

  validates :room, presence: true

  def time
    if self.available_time_id
      test = AvailableTime.find(self.available_time_id)
      test.time
    else
      "no time found"
    end
  end
end

app/models/recurser.rb
class Recurser < ActiveRecord::Base
  has_one :group, inverse_of: :recursers

  validates :name, presence: true
  validates :email, presence: true
  validates :zulip_email, :format => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= Recurser.where(id: session[:user_id]).first
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    if !session[:user_id].nil?
      current_user #sets the @_current_user variable
      @ping_success = params["ping_success"]
      puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      puts params["ping_success"]

      @sections = {
        "Checkins" => ["9:00AM", "10:30AM", "1:00PM"],
      }

      @groups = Group.order("available_time_id ASC, room ASC")
    else
      redirect_to '/login'
    end
  end

  def new
    @group = Group.new
    @available_times = AvailableTime.all
  end


  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to "/"
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)

    redirect_to "/"
    #error handling!
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to "/"
  end


  private
    def group_params
      params.require(:group).permit(:room, :time, :topic, :available_time_id)
    end
end

app/controllers/recursers_controller.rb
class RecursersController < ApplicationController
  CLIENT_ID = Rails.application.secrets.RC_API_ID
  CLIENT_SECRET = Rails.application.secrets.RC_API_SECRET
  REDIRECT_URI  = Rails.application.secrets.RC_API_URI
  SITE          = 'https://www.recurse.com'

  def start_auth
    client = create_client
    redirect_to client.auth_code.authorize_url(redirect_uri: REDIRECT_URI)
  end

  def auth_callback
    client = create_client
    code = params[:code]
    token = client.auth_code.get_token(code, redirect_uri: REDIRECT_URI)
    session["token"] = token
    user = JSON.parse(token.get("/api/v1/people/me").body)
    authed_user = {:name => user["first_name"] + " " +  user["last_name"], :email => user["email"], :zulip_email => user["email"]}
    create(authed_user)
  end


  def new
    @recurser = Recurser.new
  end

  def create(user)
    @recurser = Recurser.find_by email: user[:email]

    if @recurser
      update_session_user(@recurser.id)
      redirect_to "/"
    else
      @recurser = Recurser.new(user)
      if @recurser.save
        update_session_user(@recurser.id)
        redirect_to "/"
      else
        render 'new'
      end
    end
  end

  def edit
    current_user #sets @_current_user variable
  end

  def update
    current_user #sets @_current_user variable

    #group_id is a different edit case, it's not passed in as part of recurser_params
    if params[:group_id]
      @_current_user.update({:group_id => params[:group_id]})

      ping_success = schedule_pings


      redirect_to controller: :groups, action: :index , ping_success: ping_success.to_s
    elsif @_current_user.update(recurser_params)
      redirect_to "/"
    else
      render "edit"
    end
  end

  def leave_group
    current_user #sets @_current_user variable
    @_current_user.update({:group_id => nil})
    remove_existing_pings
    redirect_to "/"
  end


  def destroy
    @recurser = Recurser.find(params[:id])
    @recurser.destroy
    redirect_to "/"
  end


  private
  def recurser_params
    params.require(:recurser).permit(:name, :email, :group_id, :zulip_email)
  end

  def update_session_user(id)
    session[:user_id]= id
  end

  def create_client
    OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET, site: SITE)
  end

  def remove_existing_pings
    jobs = Delayed::Job.where(queue: @_current_user.email)
    jobs.each do |job|
      Delayed::Job.find(job.id).destroy
    end
  end

  def schedule_pings
    remove_existing_pings

    # find the correct time of day to ping
    # Time.parse will default to TODAY
    group = Group.find(@_current_user.group_id)
    pingtime = Time.parse(group.time)


    # checks if we're scheduling jobs for this week or next week
    # wday (3) == Weds
    weekday = Time.zone.now.wday
    if weekday <= 3
      thisweek = true
      start = weekday
    else
      thisweek = false
      start = 1
    end

    if !thisweek
      #since Time.parse defaults to today, add some days to start next Monday
      pingtime = pingtime + (86400 * (6-weekday+2))
    end

    scheduled_something = false

    # schedule the correct number of jobs on correct days
    (start..4).each do |w|
      # adds days to the pingtime(value for + is in seconds)
      dailypingtime = pingtime + (86400 * (w-start))

      # schedule a ping
      content = "Your check-in starts now in #{group.room}."
      if dailypingtime > Time.zone.now
        scheduled_something = true
        ZulipPingJob.delay(
          queue: @_current_user.email,
          run_at: dailypingtime
        ).perform_later(
          @_current_user.zulip_email,
          content
        )
      end
    end

    jobs = Delayed::Job.where(queue: @_current_user.email)
    jobs.each do |job|
      puts job
    end

    scheduled_something #return whether something was scheduled
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def ping_success_helper(ping_success)
    if ping_success == "true"
      return "Your check-ins have been scheduled."
    else
      return "Something went wrong..."
    end
  end

end

app/helpers/recursers_helper.rb
module RecursersHelper
end

app/views/groups/_group.html.erb
<div class="group group-checkin">
  <p><strong><%= group.room %> @ <%= group.time %></strong></p>



  <div class="group__topic" id="group__topic<%=group.id%>">
    <p>Topic: <%= group.topic %>
      <%= image_tag("edit.png", {:class=> "group__topic__edit-button", :id => "group__topic__edit-button" + group.id.to_s}) %>
    </p>
  </div>

  <div class="group__topic-change" id="group__topic-change<%=group.id%>">

    <%= form_for :group, url: group_path(group), method: :patch do |f| %>
      <p><%= f.text_field :topic %>

        <%= image_submit_tag("save.png", {:class=> "group__topic-change__submit-button", :id=> "group__topic-change__submit-button" + group.id.to_s}) %>

        <%= image_tag("cancel.png", {:class=> "group__topic-change__cancel-button", :id => "group__topic-change__cancel-button" + group.id.to_s}) %>
      </p>


    <% end %>

  </div>


  <br>

  <%= render group.recursers %>
  <br>



  <%= button_to 'join group', {:controller => 'recursers', :action => 'update', :group_id => group.id, :id => @_current_user["id"], :recurser => @_current_user}, {:class => "group__join-group-button", :method => :patch} %>



</div>

app/views/groups/index.html.erb
<!--RoomList = ["Djikstra", "Von Neumann", "McCarthy", "Turing", "Lovelace", "Church", "Babbage", "Hopper", "Library"] -->
<link href='https://fonts.googleapis.com/css?family=Press+Start+2P|Source+Code+Pro:400,700' rel='stylesheet' type='text/css'>

<div id="main-container">
  <div id="header-container">
    <%= image_tag("rclogo.png", :class => "rc-logo") %>
    <div id="titles-container">
      <h1 class='titles'>Sign up for Checkins</h1>
      <h4 class='titles'>For accountability and to find out what others are working on!</h4>
      <h3 class='titles'>You are logged in as: <%= @_current_user["name"] %></h3>
    </div>
    <%= image_tag("rclogo.png", :class => "rc-logo") %>

    <%= link_to image_tag("settings.png", :class => "settings-icon"), "/profile" %>

    <div class="settings__tooltip<%=" settings__tooltip-visible" if !@_current_user["group_id"]%>">If your Zulip email is different than what's in the RC database, change it here before signing up for check-ins!</div>

  </div>

  </div>

  <div class="confirmation <%=" confirmation-active" if @ping_success != nil %>">
    <%= ping_success_helper(@ping_success) %>
  </div>


  <% @sections.each do |title, times| %>
  <div class="groups-container">
    <% @groups.to_a.sort{ |g1,g2| Time.parse(g1.time) <=> Time.parse(g2.time) }.each do |group| %>
    <% if times.include?(group.time) %>
    <%= render group %>
    <% end %>
    <% end %>
    <%= link_to 'new group', 'groups/new', :class => "new-group-link" %>
  </div>
  <% end %>


  <%= button_to 'leave groups', {:controller => 'recursers', :action => 'leave_group', :id => @_current_user["id"], :recurser => @_current_user}, {:class => "group__join-group-button", :method => :patch} %>

  <div id="github-link">
    <%= image_tag("github.ico", :class => "github-icon") %>
    <a  href="https://github.com/recursecenter/wiki/wiki/Check-Ins-App-Contributors-guide">Want to contribute?</a>
  </div>

</div>

app/views/groups/new.html.erb
<link href='https://fonts.googleapis.com/css?family=Press+Start+2P|Source+Code+Pro:400,700' rel='stylesheet' type='text/css'>

<%= form_for :group, url: groups_path do |g| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <h2 class="form_header"><%= g.label :room %></h2>
    <%= g.text_field :room, :class => "form_input" %>


  <h2 class="form_header">Time (select):</h2>
    <%= g.collection_select(:available_time_id, AvailableTime.all, :id, :time, {},
    html_options = {:class => "form_element"}) %>

  <h2 class="form_header">
    <%= g.label :topic %></h2>
    <%= g.text_field :topic, :class => "form_input" %>
    <br><br>


    <%= g.submit :class => "form_element" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RcCheckins</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recursers/_recurser.html.erb
<p class="recurser">
  <%= recurser.name %>
</p>

app/views/recursers/edit.html.erb
<link href='https://fonts.googleapis.com/css?family=Press+Start+2P|Source+Code+Pro:400,700' rel='stylesheet' type='text/css'>



  <%= form_for @_current_user, url: {action: "update"}, method: "patch" do |r| %>
    <% if @_current_user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@_current_user.errors.count, "error") %> prohibited
          your account from being updated:
        </h2>
        <ul>
          <% @_current_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h2 class="form_header">
      <%= r.label "Display Name" %></h2>
      <%= r.text_field :name, :class => "form_input" %>

    <h2 class="form_header">
      <%= r.label "Zulip email" %></h2>
      <p>Change this field if the email you use on Zulip is different than the one in RC's database.</p>
      <%= r.text_field :zulip_email, :class => "form_input" %><br><br>


      <%= r.submit :value => "Update My Information", :class => "form_element" %>

  <% end %>